### ISSUE TITLE
The .gitmodules file is not updated when forking the repo (and thus when using the toolchain)

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/logistics-wizard-controller#2]
@l2fprod commented on [Tue Aug 30 2016](https://github.com/IBM-Bluemix/logistics-wizard/issues/193)

logistics-wizard uses a .gitmodules to reference its dependencies.

This is mainly used by the unit tests to start the logistics-wizard-erp module. See https://github.com/IBM-Bluemix/logistics-wizard-toolchain/blob/master/.bluemix/controller.pipeline.yml#L103.

However let's say you are forking the repos (controller, erp, etc) of the projects (manually or through the toolchain), the .gitmodules file (https://github.com/IBM-Bluemix/logistics-wizard/blob/master/.gitmodules) is not updated and still contain the reference to the IBM-Bluemix organization.

The approach should be changed. What these unit tests are doing is closer to integration tests and here we would want to run this into an environment where we deploy all our modules, wire them then run integration tests. The unit tests should focus on testing the specificities of the controller.

**Comment by l2fprod** [comment]
Interesting reads in this context:
- http://www.dev9.com/article/2015/5/zgotxg9hajgch1mg0d2hgbfgsf46ho
- http://martinfowler.com/articles/microservice-testing/#conclusion-summary

For the controller, I would use mock responses for the ERP service and focus on testing the data conversion the controller is doing. There are some tests that test the contract of the ERP itself. For those, ensure they are covered in the ERP service and remove them.

Once the focus is back on the unit tests, we can look into a system test solution where we instantiate a full LW deployment.

**Comment by l2fprod** [comment]
A mockup library for python https://github.com/gabrielfalcao/HTTPretty

**Comment by l2fprod** [comment]
Pull request https://github.com/IBM-Bluemix/logistics-wizard-controller/pull/4

**Comment by rvennam** [comment]
lgtm
