### ISSUE TITLE
Use "bx wsk" to retrieve the Cloud Function key (OPENWHISK_AUTH)

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/logistics-wizard-controller#30]
with the new "bx wsk" it should no longer be needed to require the user to input the OPENWHISK_AUTH key. We should be able to retrieve it automatically.

**Comment by van-ibm** [comment]
Fixed in june-sprint commit dc10dc26069a35fc1fbbd933114021add0ebaf9b.
